/**
 * Game state type constants.
 * Extracted from gameState.js for modularity.
 */

export const GamePhase = {
    LOBBY: "LOBBY",
    JOINING: "JOINING",
    SESSION_READY: "SESSION_READY",
    IN_ROUND: "IN_ROUND",
    ROUND_RESOLVED: "ROUND_RESOLVED",
    SESSION_RESOLVED: "SESSION_RESOLVED",
};

export const ActionType = {
    APP_INIT: "APP_INIT",
    PLAYER_SESSION_LOADED: "PLAYER_SESSION_LOADED",
    MODELS_LOADED: "MODELS_LOADED",
    LOBBY_TAB_SELECTED: "LOBBY_TAB_SELECTED",
    INTENT_START_MATCH: "INTENT_START_MATCH",
    INTENT_RECOVER_SESSION: "INTENT_RECOVER_SESSION",
    INTENT_START_ROUND: "INTENT_START_ROUND",
    INTENT_SUBMIT_ANSWER: "INTENT_SUBMIT_ANSWER",
    INTENT_NEXT: "INTENT_NEXT",
    INTENT_GIVE_UP: "INTENT_GIVE_UP",
    GIVE_UP_SUCCEEDED: "GIVE_UP_SUCCEEDED",
    GIVE_UP_FAILED: "GIVE_UP_FAILED",
    INTENT_SELECT_CHOICE: "INTENT_SELECT_CHOICE",
    INTENT_SET_FREE_MODE: "INTENT_SET_FREE_MODE",
    INTENT_UPDATE_FREE_TEXT: "INTENT_UPDATE_FREE_TEXT",
    INTENT_UPDATE_INT_VALUE: "INTENT_UPDATE_INT_VALUE",
    INTENT_CLEAR_ANSWER: "INTENT_CLEAR_ANSWER",
    INTENT_SET_TOP_TAB: "INTENT_SET_TOP_TAB",
    INTENT_TOGGLE_SCRATCHPAD: "INTENT_TOGGLE_SCRATCHPAD",
    INTENT_SCRATCHPAD_TEXT: "INTENT_SCRATCHPAD_TEXT",
    INTENT_CALC_EXPR: "INTENT_CALC_EXPR",
    INTENT_CALC_RESULT: "INTENT_CALC_RESULT",
    INTENT_CLEAR_SCRATCHPAD: "INTENT_CLEAR_SCRATCHPAD",
    INTENT_PEEK_REASONING: "INTENT_PEEK_REASONING",
    MATCH_END_DISMISSED: "MATCH_END_DISMISSED",
    LANDING_ACKED: "LANDING_ACKED",
    WS_OPENED: "WS_OPENED",
    WS_CLOSED: "WS_CLOSED",
    SERVER_EVENT_RECEIVED: "SERVER_EVENT_RECEIVED",
    TIMER_TICK: "TIMER_TICK",
    VS_TRANSITION_SWITCHED: "VS_TRANSITION_SWITCHED",
    VS_TRANSITION_DONE: "VS_TRANSITION_DONE",
};

export const EffectType = {
    WS_CONNECT: "WS_CONNECT",
    WS_SEND: "WS_SEND",
    WS_CLOSE: "WS_CLOSE",
    TOAST: "TOAST",
    SET_HASH: "SET_HASH",
    SAVE_NICKNAME: "SAVE_NICKNAME",
    PLAY_VS_TRANSITION: "PLAY_VS_TRANSITION",
    CANCEL_VS_TRANSITION: "CANCEL_VS_TRANSITION",
    START_TICKER: "START_TICKER",
    STOP_TICKER: "STOP_TICKER",
    TERMINATE_SESSION: "TERMINATE_SESSION",
};
